{{- if not .Values.elasticsearch.external.url }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-curator
  labels:
{{- include "logging.labels" . | indent 2}}
data:
  actions.yml: |+
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 7 days (based on index creation_date).
          Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: age
          source: creation_date
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
          exclude:
        - filtertype: kibana
          exclude: True

  curator.yml: |+
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - ${ES_HOST}
      port: ${ES_PORT}
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 300
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-curator
  labels:
{{- include "logging.labels" . | indent 2}}
spec:
  schedule: "0 11 1,15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: es-curator
            image: {{ .Values.es_curator_image.registry }}{{ .Values.es_curator_image.repository }}:{{ .Values.es_curator_image.tag }}
            env:
            - name: ES_HOST
              value: "{{ .Release.Name}}-client"
            - name: ES_PORT
              value: "9200"
            command: ["/curator/curator", "--config", "/config/curator.yml", "/config/actions.yml"]
            volumeMounts:
            - name: curator
              mountPath: "/config"
          restartPolicy: OnFailure
          volumes:
          - name: curator
            configMap:
              name: {{ .Release.Name }}-curator
{{- end }}