{{- if not .Values.elasticsearch.external.url }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ .Release.Name }}-data
  labels:
{{- include "logging.labels" . | indent 2}}
spec:
  ports:
  - name: http
    port: 9200
    targetPort: http
  selector:
{{- include "logging.metadata.labels" . | indent 2}}
    node: es
    type: data
  type: ClusterIP
{{- end }}