{{- if not .Values.elasticsearch.external.url }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ .Release.Name }}-master
  labels:
    node: es
{{- include "logging.labels" . | indent 2}}
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Release.Name }}-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
{{- include "logging.metadata.labels" . | indent 4}}
      type: master
      node: es
  template:
    metadata:
      labels:
{{- include "logging.metadata.labels" . | indent 6 }}
        type: master
        node: es
        kubernetes.io/cluster-service: "true"
    spec:
      {{ with .Values.master.affinity -}}     
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{ with .Values.master.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{ end }}
      serviceAccountName: {{ .Release.Name }}-priv
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.repository }}/elasticsearch/elasticsearch-oss:{{ .Values.app_version }}
        name: {{ template "logging.name" . }}
        resources:
          # need more cpu upon initialization, therefore burstable class
{{ toYaml .Values.master.resources | indent 10 }}
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-data
          mountPath: /data
{{- if .Values.elk.snapshot.enabled }}
        - name: es-snapshot
          mountPath: /snapshot
{{- end }}          
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "MINIMUM_MASTER_NODES"
          value: {{ .Values.master.minimum_nodes | quote }}
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.master.heap_size }} -Xmx{{ .Values.master.heap_size }} {{ .Values.elk.additional_jvm_params }}"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
      volumes:
      - name: elasticsearch
        configMap:
          name: {{ .Release.Name }}
{{- if .Values.elk.snapshot.enabled }}
      - name: es-snapshot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshot-pvc
{{- end }}    
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: {{ .Values.init_container_image.registry }}{{ .Values.init_container_image.repository }}:{{ .Values.init_container_image.tag }}
        command: ["sh","-c","/sbin/sysctl -w vm.max_map_count=262144 || true && chown 1000:1000 /data && if [ -d /snapshot ]; then chown 1000:1000 /snapshot ; fi"]
        name: init
        volumeMounts:
        - name: es-data
          mountPath: /data
{{- if .Values.elk.snapshot.enabled }}
        - name: es-snapshot
          mountPath: /snapshot
{{- end }}          
        securityContext:
          privileged: true  
          runAsUser: 0
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      {{- with .Values.storage_class }}
      storageClassName: {{ . | quote }}
      {{- end }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.master.storage }}
{{- end }}