{{- if .Values.elk.snapshot.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-snapshot-pvc
  labels:
{{- include "logging.labels" . | indent 2}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.elk.snapshot.size }}
  {{- if .Values.elk.snapshot.storage_class }}
  storageClassName: {{ .Values.elk.snapshot.storage_class | quote }}
  {{ else }}
  storageClassName: {{ .Values.storage_class | quote }}
  {{- end }}
{{- end}}