apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-init
  labels:
{{- include "logging.labels" . | indent 2}}
data:
  init.sh: |-
    #!/bin/bash

    set -e    

    if [[ $1 == http* ]]; then
      # extract the protocol
      proto="$(echo $1 | grep :// | sed -e's,^\(.*://\).*,\1,g')"
      # remove the protocol
      url="$(echo ${1/$proto/})"
      # extract the user (if any)
      user="$(echo $url | grep @ | cut -d@ -f1)"
      # extract the host and port
      hostport="$(echo ${url/$user@/} | cut -d/ -f1)"
      # by request host without port    
      host="$(echo $hostport | sed -e 's,:.*,,g')"
      # by request - try to extract the port
      port=`echo $hostport | grep : | cut -d: -f2`
      if [[ -z $port ]]; then
        if [[ $proto = http:// ]]; then
          port=80
        fi
        if [[ $proto == https:// ]]; then 
          port=443 
        fi
     fi 
     else
       host=$1
       port=$2
     fi  
     
     echo "check for host: $host at port: $port"
     
     while ! nc -z -w 2 $host $port; do 
       echo "connecting $host:$port"
       sleep 2
     done  
