{{ if .Values.journalbeat.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-journalbeat
  labels:
{{- include "logging.labels" . | indent 2 }}
    type: journalbeat
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
{{- include "logging.metadata.labels" . | indent 4 }}
      k8s-app: journalbeat      
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "logging.metadata.labels" . | indent 6}}
        k8s-app: journalbeat
    spec:
      securityContext:
        runAsUser: 0
      {{ with .Values.journalbeat.affinity }}     
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{ with .Values.journalbeat.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{ end }}
      serviceAccountName: {{ .Release.Name }}-priv
      terminationGracePeriodSeconds: 30
      priorityClassName: logging-critical
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init  
        imagePullPolicy: Always
        image: {{ .Values.init_container_image.registry }}{{ .Values.init_container_image.repository }}:{{ .Values.init_container_image.tag }}
{{if not .Values.elasticsearch.external.url }}
        {{- if not .Values.logstash_indexer.beats}}      
        command: ["sh","-c","/init.sh {{ .Release.Name}}-client 9200 && /init.sh {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}.kafka 9092"]
        {{ else }}
        command: ["sh","-c","/init.sh {{ .Release.Name}}-client 9200 && /init.sh {{ .Release.Name}}-logstash-indexer 5045"]
        {{- end }}
{{ else }}
        {{- if not .Values.logstash_indexer.beats}}              
        command: ["sh","-c","/init.sh {{ .Values.elasticsearch.external.url }} && /init.sh {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}.kafka 9092"]
        {{ else }}
        command: ["sh","-c","/init.sh {{ .Values.elasticsearch.external.url }} && /init.sh {{ .Release.Name}}-logstash-indexer 5045"]
        {{- end }}
{{ end }}              
        volumeMounts:
        - mountPath: "/init.sh"
          subPath: init.sh
          name: init 
      containers:
      - name: journalbeat
        image: {{ .Values.repository}}/beats/journalbeat:{{ .Values.app_version}}
        #image: mheese/journalbeat:latest
        args: [
          "-c", "/usr/share/journalbeat/journalbeat.yml",
          "-e"
        ]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /usr/share/journalbeat/journalbeat.yml
          readOnly: true
          subPath: journalbeat.yml
        - name: journallog
          mountPath: {{ .Values.journalbeat.path}}
        - name: systemd
          mountPath: /run/systemd
          readOnly: true
        - name: data
          mountPath: /usr/share/journalbeat/data 
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755  
      - name: config
        configMap:
          name: {{ .Release.Name}}-journalbeat-config
      - name: journallog
        hostPath:
          path: {{ .Values.journalbeat.path}}
          type: Directory
      - name: systemd
        hostPath:
          path: /run/systemd 
      - name: data
        emptyDir: {}
{{ end }}