{{- if not .Values.logstash_indexer.beats }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
{{- include "logging.labels" . | indent 2}}
spec:
  ports:
  - port: 9092
    name: kafka
  - port: 9093
    name: broker
  - port: 12345
    name: jmx
  clusterIP: None
  selector:
{{- include "logging.metadata.labels" . | indent 2}}
    type: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
{{- include "logging.labels" . | indent 2}}
spec:
  ports:
  - port: 9092
    name: kafka
  selector:
{{- include "logging.metadata.labels" . | indent 2}}
    type: kafka
{{ range $kafkaId := until (.Values.kafka.replicas | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-kafka-{{ $kafkaId }}
  labels:
  {{- include "logging.labels" $ | indent 2}}
spec:
  ports:
    - port: 9092
      name: kafka
    - port: 9093
      name: broker
    - port: 12345
      name: jmx
  selector:
  {{- include "logging.metadata.labels" $ | indent 2}}
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-kafka-{{ $kafkaId }}
    type: kafka
{{ end }}
{{- end }}