apiVersion: v1
kind: Secret
metadata:
  name: logstash-indexer-elasticsearch
type: Opaque
data:
  host: {{ if not .Values.elasticsearch.external.url }}{{ .Release.Name |  printf "%s-data" | b64enc }}{{ else }}{{ .Values.elasticsearch.external.url | b64enc }}{{ end }}
{{ if .Values.elasticsearch.external.user }}
  user: {{ .Values.elasticsearch.external.user | b64enc }}
{{ end }}
{{ if .Values.elasticsearch.external.password }}
  password: {{ .Values.elasticsearch.external.password | b64enc }}
{{ end }}
