apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-logstash-indexer
  labels:
{{- include "logging.labels" . | indent 2}}
spec:
  replicas: {{ .Values.logstash_indexer.replicas}}
  selector:
    matchLabels:
{{- include "logging.metadata.labels" . | indent 4}}
      type: logstash-indexer
  template:
    metadata:
      labels:
{{- include "logging.metadata.labels" . | indent 6}}
        type: logstash-indexer
    spec:
      {{ with .Values.logstash_indexer.affinity -}}     
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{ with .Values.logstash_indexer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{ end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init
        imagePullPolicy: Always
        image: {{ .Values.init_container_image.registry }}{{ .Values.init_container_image.repository }}:{{ .Values.init_container_image.tag }}
{{if not .Values.elasticsearch.external.url }}
        {{- if not .Values.logstash_indexer.beats}}
        command: ["sh","-c","/init.sh {{ .Release.Name}}-client 9200 && /init.sh {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}.kafka 9092"]
        {{ else }}
        command: ["sh","-c","/init.sh {{ .Release.Name}}-client 9200"]
        {{- end }}
{{ else }}        
        {{- if not .Values.logstash_indexer.beats}}
        command: ["sh","-c","/init.sh {{ .Values.elasticsearch.external.url }} && /init.sh {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}.kafka 9092"]
        {{ else }}
        command: ["sh","-c","/init.sh {{ .Values.elasticsearch.external.url }}"]
        {{- end }}
{{ end }}
        volumeMounts:
        - mountPath: "/init.sh"
          subPath: init.sh
          name: init     
      containers:  
      - name: logstash-indexer
        image: {{ .Values.repository }}/logstash/logstash-oss:{{ .Values.app_version }}
        {{- if .Values.logstash_indexer.beats }}
        ports:
        - containerPort: 5044
          name: containers
          protocol: TCP
        - containerPort: 5045
          protocol: TCP
          name: journals
        {{- end }}      
        env:
        - name: ELASTICSEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: logstash-indexer-elasticsearch
              key: host            
{{ if .Values.elasticsearch.external.user }}
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: logstash-indexer-elasticsearch
              key: user 
{{ end }}
{{ if .Values.elasticsearch.external.password }}
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logstash-indexer-elasticsearch
              key: password
{{ end }}              
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-svc:9092
        - name: LS_JAVA_OPTS
          value: "-Xms{{ .Values.logstash_indexer.heap_size }} -Xmx{{ .Values.logstash_indexer.heap_size }} {{ .Values.elk.additional_jvm_params }}"
        resources:
{{ toYaml .Values.logstash_indexer.resources | indent 10 }}  
        volumeMounts:
        - mountPath: "/usr/share/logstash/config/logstash.yml"
          subPath: logstash.yml
          name: config
        - mountPath: "/usr/share/logstash/config/pipelines.yml"
          subPath: pipelines.yml
          name: config
        - mountPath: "/usr/share/logstash/config/log4j2.properties"
          subPath: log4j2.properties
          name: config
        {{ range $path, $bytes := .Files.Glob "logstash-indexer-pipelines/*-pipeline.conf" }}
        - mountPath: {{ printf "%s%s" "/usr/share/logstash/pipeline/" (base $path) }}
          subPath: {{ printf "%s" (base $path) }}
          name: pipelines
        {{- end -}}
        {{ range $path, $bytes := .Files.Glob "indices-templates/*_template.json" }}
        - mountPath: {{ printf "%s%s" "/usr/share/logstash/config/" (base $path) }}
          subPath: {{ printf "%s" (base $path) }}
          name: indices-templates
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name}}-logstash-indexer
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755    
      - name: pipelines
        configMap:
          name: {{ .Release.Name}}-logstash-indexer-pipelines
      - name: indices-templates
        configMap:
          name: {{ .Release.Name}}-indices-templates
