{{- if .Values.logstash_indexer.beats }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-logstash-indexer
  labels:
{{- include "logging.labels" . | indent 2}}
spec:
  ports:
  - name: containers
    port: 5044
    targetPort: containers
  - name: journals
    port: 5045
    targetPort: journals  
  selector:
{{- include "logging.metadata.labels" . | indent 2}}
    type: logstash-indexer
  type: ClusterIP
{{- end }}  
