{{- $global := . }}
{{- range $i, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
type: tls
data:
  tls.key: {{ $secret.key | b64enc }}
  tls.crt: {{ $secret.crt | b64enc }}
{{- end }}